name: PR_CI
on:
  pull_request:
    branches:
      - develop
env:
  CACHE_NODE_MODULES_PATH: |
    node_modules
    */*/node_modules

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get lockfile hash
        id: lockfile_hash
        run: echo "::set-output name=hash::${{ hashFiles('**/yarn.lock') }}"

      - name: Check cached node_modules
        id: check_cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: ${{ steps.lockfile_hash.outputs.hash }}

      - name: Install dependencies
        if: steps.check_cache.outputs.cache-hit == ''
        run: yarn install
    outputs:
      cache_node_modules_key: ${{ steps.lockfile_hash.outputs.hash }}

  run-lint:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check cached node_modules
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: ${{ needs.prepare.outputs.cache_node_modules_key }}

      - name: Run lint
        run: yarn lint

  run-build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check cached node_modules
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: ${{ needs.prepare.outputs.cache_node_modules_key }}

      - name: Run build
        run: yarn workspace @github-dm/chrome-ext build
